#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <string>
#include <vector>
using namespace std;

enum TILES
{
  EMPTY_TILE = '-',
  SOLID_TILE = 'O',
  DESTRUCTIBLE_TILE = 'X',
  BORDER = '*',
  BORDER_TOP = 'T',
  BORDER_BOTTOM = 'B',
  BORDER_LEFT = 'L',
  BORDER_RIGHT = 'R',
  CORNER_TOP_LEFT = '<',
  CORNER_TOP_RIGHT = '>',
  CORNER_BOTTOM_LEFT = 'v',
  CORNER_BOTTOM_RIGHT = '^',
};

const vector<char> COLLISION_TILES = {DESTRUCTIBLE_TILE, BORDER, SOLID_TILE, CORNER_TOP_LEFT, CORNER_TOP_RIGHT, CORNER_BOTTOM_LEFT, CORNER_BOTTOM_RIGHT, BORDER_TOP, BORDER_BOTTOM, BORDER_LEFT, BORDER_RIGHT};
const vector<char> CORNER_TILES = {CORNER_TOP_LEFT, CORNER_TOP_RIGHT, CORNER_BOTTOM_LEFT, CORNER_BOTTOM_RIGHT};
const vector<char> BORDER_TILES = {BORDER, BORDER_TOP, BORDER_BOTTOM, CORNER_TOP_LEFT, CORNER_TOP_RIGHT, CORNER_BOTTOM_LEFT, CORNER_BOTTOM_RIGHT, BORDER_LEFT, BORDER_RIGHT};

const char PLAYER_ONE_ID = '1';
const char PLAYER_TWO_ID = '2';

const string RIGHT = "right";
const string LEFT = "left";
const string UP = "up";
const string DOWN = "down";

const int EXPLOSION_ANIMATION_FRAMES = 4;
const int BOMB_ANIMATION_FRAMES = 3;
const int PLAYER_ANIMATION_FRAMES = 3;
const int PLAYER_TEXTURE_UP_DEFAULT_FRAME = 1;
const int PLAYER_TEXTURE_DOWN_DEFAULT_FRAME = 1;
const int PLAYER_TEXTURE_LEFT_DEFAULT_FRAME = 0;
const int PLAYER_TEXTURE_RIGHT_DEFAULT_FRAME = 0;

#endif
